### PR TITLE
Usage file: Fix path to image

### PR DESCRIPTION
**Pull request by schenker-dr**
### What was done.
Changed the path to the image in the JP / EN usage.adoc.

### How it was tested
Previewing images now works.

Before:
image

Now:
image

### Comment to repository owner
[DeepL] お疲れ様でした。画像を反映するようにパスを編集しましたが、おそらく画像は別のフォルダに属しています。
Thank you for your work. I have edited the path to reflect the image, but perhaps the image belongs in a different folder.

### CODE REVIEW

**Comment by schenker-dr** [comment]
@MizunagiKB [DeepL] お時間のあるときにでも復習してください。

**Comment by MizunagiKB** [comment]
@fdranky 

Thank you for your pull request.
We understand that you may have submitted it because the display appears to be incorrect, but the absence of image display is intentional.

Originally, we had set it up so that it could be read on GitHub, but as the number of GDCubism users has increased, we have introduced a site generator that creates searchable documents and versions from 0.6 onwards.

Due to this switch, the asciiDoc for GDCubism does not display correctly as is, and it is only made public by generating a site with Antora.

There is a link on the right side of GDCubism’s GitHub, and the relevant part can be checked at the following location: 

https://mizunagikb.github.io/gd_cubism/gd_cubism/0.6/en/usage.html

This seems to be a problem caused by the README.adoc being able to display incompletely. It might be a good idea to add a comment to the README.adoc.

**Comment by schenker-dr** [comment]
@MizunagiKB Thank you for your quick reply.
Understood! As you are using the site generator I will close this PR.

**Comment by MizunagiKB** [comment]
@fdranky 
You were previously trying to fix an asciiDoc page, but I thought it might be because the README.en.adoc at the entrance itself is linking to an undesirable location.

Therefore, for the GDCubism's README.en.adoc link that is left halfway, if you are viewing from GitHub or VisualStudioCode, I have modified it to switch to a link to the already created manual page.

This has been fixed in the following pull request. https://github.com/MizunagiKB/gd_cubism/pull/84

**Pull request closed without merging**
